begin;

create schema if not exists mqs;

create table if not exists mqs.teacher (
  id integer generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  phone_number text,
  "group" text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists mqs.groups (
  id integer generated by default as identity primary key,
  name text not null,
  teacher_id integer not null references mqs.teacher(id),
  color_code text not null default 'rose',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists mqs.students (
  id integer generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  birth_year integer,
  phone text,
  father_phone text,
  mother_phone text,
  "group" text,
  group_id integer not null references mqs.groups(id),
  teacher_id integer references mqs.teacher(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists mqs.homework_assignments (
  id integer generated by default as identity primary key,
  student_id integer not null references mqs.students(id),
  assigned_by_user_id integer not null,
  name text not null,
  description text not null,
  due_date timestamptz not null,
  reminder_sent boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists mqs.attendance_sessions (
  id integer generated by default as identity primary key,
  session_date date not null,
  label text not null,
  sequence_on_date integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists mqs.attendance_records (
  id integer generated by default as identity primary key,
  student_id integer not null references mqs.students(id),
  attendance_session_id integer not null references mqs.attendance_sessions(id),
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

commit;
