begin;

create table if not exists mqs.cohorts (
  id integer generated by default as identity primary key,
  course_id integer not null references mqs.courses(id),
  name text not null,
  tag text not null,
  status text not null default 'active',
  starts_at date,
  ends_at date,
  previous_cohort_id integer references mqs.cohorts(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint cohorts_tag_format check (tag ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create unique index if not exists cohorts_course_tag_active_unique
  on mqs.cohorts (course_id, tag)
  where deleted_at is null;

create table if not exists mqs.cohort_enrollments (
  id integer generated by default as identity primary key,
  course_id integer not null references mqs.courses(id),
  cohort_id integer not null references mqs.cohorts(id),
  student_id integer not null references mqs.students(id),
  enrollment_type text not null default 'new',
  outcome text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index if not exists cohort_enrollments_active_unique
  on mqs.cohort_enrollments (cohort_id, student_id)
  where deleted_at is null;

insert into mqs.cohorts (course_id, name, tag, status)
select courses.id, courses.name || ' Default Cohort', courses.slug || '-default', 'active'
from mqs.courses courses
where not exists (
  select 1
  from mqs.cohorts cohorts
  where cohorts.course_id = courses.id
    and cohorts.deleted_at is null
);

do $$
declare
  app_table text;
begin
  foreach app_table in array array[
    'students',
    'teacher',
    'groups',
    'homework_assignments',
    'memorization_pages',
    'page_point_awards',
    'manual_point_transactions',
    'page_point_tiers',
    'attendance_sessions',
    'attendance_records'
  ]
  loop
    execute format('alter table mqs.%I add column if not exists cohort_id integer references mqs.cohorts(id)', app_table);
    execute format(
      'update mqs.%I rows set cohort_id = cohorts.id
       from mqs.cohorts cohorts
       where rows.course_id = cohorts.course_id
         and rows.cohort_id is null
         and cohorts.deleted_at is null',
      app_table
    );
    execute format('create index if not exists %I on mqs.%I (cohort_id)', app_table || '_cohort_id_idx', app_table);
  end loop;
end $$;

commit;
