begin;

create table if not exists mqs.memorization_pages (
  id integer generated by default as identity primary key,
  student_id integer not null references mqs.students(id),
  page integer not null,
  memorized_on date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint memorization_pages_page_check check (page between 1 and 604)
);

create table if not exists mqs.page_point_awards (
  id integer generated by default as identity primary key,
  memorization_page_id integer not null unique references mqs.memorization_pages(id),
  student_id integer not null references mqs.students(id),
  rule_name text not null,
  snapshot text not null,
  points integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists mqs.manual_point_transactions (
  id integer generated by default as identity primary key,
  student_id integer not null references mqs.students(id),
  transaction_date date not null default current_date,
  amount integer not null,
  reason text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint manual_point_transactions_reason_present check (length(trim(reason)) > 0)
);

create table if not exists mqs.page_point_tiers (
  id integer generated by default as identity primary key,
  min_pages integer not null,
  max_pages integer,
  points integer not null,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint page_point_tiers_min_positive check (min_pages > 0),
  constraint page_point_tiers_max_valid check (max_pages is null or max_pages >= min_pages)
);

create index if not exists memorization_pages_student_date_idx
  on mqs.memorization_pages (student_id, memorized_on)
  where deleted_at is null;

create unique index if not exists memorization_pages_student_page_active_unique
  on mqs.memorization_pages (student_id, page)
  where deleted_at is null;

create index if not exists page_point_awards_student_idx
  on mqs.page_point_awards (student_id)
  where deleted_at is null;

create index if not exists manual_point_transactions_student_date_idx
  on mqs.manual_point_transactions (student_id, transaction_date)
  where deleted_at is null;

insert into mqs.page_point_tiers (min_pages, max_pages, points, name)
values
  (1, 1, 10, '1 page/day'),
  (2, 2, 20, '2 pages/day'),
  (3, null, 30, '3+ pages/day')
on conflict do nothing;

do $rls$
declare
  app_table text;
begin
  if to_regprocedure('public.is_app_admin()') is null then
    raise notice 'Skipping points RLS setup because public.is_app_admin() does not exist.';
    return;
  end if;

  grant usage on schema mqs to authenticated;
  revoke usage on schema mqs from anonymous;

  foreach app_table in array array[
    'memorization_pages',
    'page_point_awards',
    'manual_point_transactions',
    'page_point_tiers'
  ]
  loop
    execute format('alter table mqs.%I enable row level security', app_table);
    execute format('alter table mqs.%I force row level security', app_table);
    execute format('revoke all on mqs.%I from anonymous', app_table);
    execute format('grant select, insert, update, delete on mqs.%I to authenticated', app_table);

    execute format('drop policy if exists app_admin_select on mqs.%I', app_table);
    execute format('drop policy if exists app_admin_insert on mqs.%I', app_table);
    execute format('drop policy if exists app_admin_update on mqs.%I', app_table);
    execute format('drop policy if exists app_admin_delete on mqs.%I', app_table);

    execute format(
      'create policy app_admin_select on mqs.%I for select to authenticated using (public.is_app_admin())',
      app_table
    );
    execute format(
      'create policy app_admin_insert on mqs.%I for insert to authenticated with check (public.is_app_admin())',
      app_table
    );
    execute format(
      'create policy app_admin_update on mqs.%I for update to authenticated using (public.is_app_admin()) with check (public.is_app_admin())',
      app_table
    );
    execute format(
      'create policy app_admin_delete on mqs.%I for delete to authenticated using (public.is_app_admin())',
      app_table
    );
  end loop;

  grant usage, select on all sequences in schema mqs to authenticated;
  revoke all on all sequences in schema mqs from anonymous;
end $rls$;

commit;
