begin;

create schema if not exists mqs;

alter table mqs.students
  add column if not exists father_name text,
  add column if not exists school_year integer,
  add column if not exists residence text,
  add column if not exists transport_required boolean not null default false,
  add column if not exists registration_submitted_at timestamptz;

create table if not exists mqs.awqaf_certificate_pages (
  id integer generated by default as identity primary key,
  course_id integer not null references mqs.courses(id),
  student_id integer not null references mqs.students(id),
  page integer not null,
  certified_on date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint awqaf_certificate_pages_page_check check (page between 1 and 604)
);

create index if not exists awqaf_certificate_pages_student_date_idx
  on mqs.awqaf_certificate_pages (course_id, student_id, certified_on)
  where deleted_at is null;

create unique index if not exists awqaf_certificate_pages_course_student_page_active_unique
  on mqs.awqaf_certificate_pages (course_id, student_id, page)
  where deleted_at is null;

create or replace function mqs.enforce_course_relations()
returns trigger
language plpgsql
as $$
begin
  if tg_table_name = 'students' then
    perform mqs.assert_same_course('mqs.groups', new.group_id, new.course_id, 'group');
    perform mqs.assert_same_course('mqs.teacher', new.teacher_id, new.course_id, 'teacher');
  elsif tg_table_name = 'groups' then
    perform mqs.assert_same_course('mqs.teacher', new.teacher_id, new.course_id, 'teacher');
  elsif tg_table_name = 'homework_assignments' then
    perform mqs.assert_same_course('mqs.students', new.student_id, new.course_id, 'student');
  elsif tg_table_name = 'memorization_pages' then
    perform mqs.assert_same_course('mqs.students', new.student_id, new.course_id, 'student');
  elsif tg_table_name = 'awqaf_certificate_pages' then
    perform mqs.assert_same_course('mqs.students', new.student_id, new.course_id, 'student');
  elsif tg_table_name = 'page_point_awards' then
    perform mqs.assert_same_course('mqs.memorization_pages', new.memorization_page_id, new.course_id, 'memorization page');
    perform mqs.assert_same_course('mqs.students', new.student_id, new.course_id, 'student');
  elsif tg_table_name = 'manual_point_transactions' then
    perform mqs.assert_same_course('mqs.students', new.student_id, new.course_id, 'student');
  elsif tg_table_name = 'attendance_records' then
    perform mqs.assert_same_course('mqs.students', new.student_id, new.course_id, 'student');
    perform mqs.assert_same_course('mqs.attendance_sessions', new.attendance_session_id, new.course_id, 'attendance session');
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_course_relations on mqs.awqaf_certificate_pages;
create trigger enforce_course_relations
  before insert or update on mqs.awqaf_certificate_pages
  for each row
  execute function mqs.enforce_course_relations();

do $rls$
begin
  if to_regprocedure('public.is_app_admin()') is null then
    raise notice 'Skipping awqaf certificate RLS setup because public.is_app_admin() does not exist.';
    return;
  end if;

  grant usage on schema mqs to authenticated;
  revoke usage on schema mqs from anonymous;

  alter table mqs.awqaf_certificate_pages enable row level security;
  alter table mqs.awqaf_certificate_pages force row level security;
  revoke all on mqs.awqaf_certificate_pages from anonymous;
  grant select, insert, update, delete on mqs.awqaf_certificate_pages to authenticated;

  drop policy if exists app_admin_select on mqs.awqaf_certificate_pages;
  drop policy if exists app_admin_insert on mqs.awqaf_certificate_pages;
  drop policy if exists app_admin_update on mqs.awqaf_certificate_pages;
  drop policy if exists app_admin_delete on mqs.awqaf_certificate_pages;

  create policy app_admin_select on mqs.awqaf_certificate_pages
    for select to authenticated
    using (public.is_app_admin());

  create policy app_admin_insert on mqs.awqaf_certificate_pages
    for insert to authenticated
    with check (public.is_app_admin());

  create policy app_admin_update on mqs.awqaf_certificate_pages
    for update to authenticated
    using (public.is_app_admin())
    with check (public.is_app_admin());

  create policy app_admin_delete on mqs.awqaf_certificate_pages
    for delete to authenticated
    using (public.is_app_admin());

  grant usage, select on all sequences in schema mqs to authenticated;
  revoke all on all sequences in schema mqs from anonymous;
end $rls$;

notify pgrst, 'reload schema';

commit;
